export const BUSINESS_ACTIONS = {
  BUSINESS_REQUEST: "BUSINESS_REQUEST",
  BUSINESS_SUCCESS: "BUSINESS_SUCCESS",
  BUSINESS_FAILURE: "BUSINESS_FAILURE"
};

export const LISTING_ACTIONS = {
  LISTING_REQUEST: "LISTING_REQUEST",
  LISTING_SUCCESS: "LISTING_SUCCESS",
  LISTING_FAILURE: "LISTING_FAILURE"
};
